### ISSUE TITLE
Feature Request: Access/Edit SD card from with the WebUI or the ability to mount locally

### ISSUE THREAD

**Issue by aptonline** [FujiNetWIFI/fujinet-firmware#468]
Have the ability to either access/edit the SD card from within the WebUI or the ability to mount the SD card over the network so that you can download/upload content correctly without the need to remove the card and mount it.

**Comment by mozzwald** [comment]
as of firmware v1.4 you can use WebDAV to access files on the SD card with the url http://fujinet/dav or http://192.168.0.100/dav (use correct ip address of fujinet)
