### ISSUE TITLE
Cleanup the ifdefs where possible

### ISSUE THREAD

**Issue by DaBaDa79** [FujiNetWIFI/fujinet-firmware#699]
There are a lot of `#ifdef DEBUG`s although not necessary because the enclosed code itself is also enclosed by the same `#ifdef`. This is especially the case with the different variations of the `Debug_print()` function. Therefore the `#ifdef DEBUG`in the main code can be removed.

**Comment by tschak909** [comment]
You have a go, @DaBaDa79 .

**Comment by mozzwald** [comment]
fixed in #700
