### ISSUE TITLE
ATX file writes are not supported, preventing AR City from running

### ISSUE THREAD

**Issue by crdotson** [FujiNetWIFI/fujinet-firmware#763]
Writes to ATX files are not implemented.  This prevents Alternate Reality - The City from running, as part of the copy protection is to write to one of the disks.  

It will load up to the point where you would actually start playing, and then go into an infinite loop, with Fujinet console messages of DISK WRITE NOT IMPLEMENTED from lib/media/atari/diskType.cpp .

**Comment by mozzwald** [comment]
As you've figured out, ATX files are read only with Fujinet. I don't forsee this being added anytime soon. A quick search shows there are ways to convert ATX to ATR which is writable with Fujinet. Or, you can try to find an already converted disk image of the disk you want to be writable.
