### ISSUE TITLE
Missing Timezone (Alaska)

### ISSUE THREAD

**Issue by akhepcat** [FujiNetWIFI/fujinet-firmware#785]
Maybe i'm the first in Alaska to notice, but I can't set my timezone correctly, as it doesn't appear in the dropdown list.

AKST = UTC−09:00
AKDT = UTC−08:00

**Comment by tschak909** [comment]
Added to master, and if you'd like to test, it'll be in a nightly tomorrow. :)
Thank you for bringing this to our attention.

**Comment by akhepcat** [comment]
Awesome, thank you!

**Comment by akhepcat** [comment]
Flashed successfully,  was able to set the TZ, and time is now appropriate for my locale!

thanks again for the quick turnaround
