### ISSUE TITLE
Cant get WebDav to work

### ISSUE THREAD

**Issue by sideburn** [FujiNetWIFI/fujinet-firmware#818]
I have updated to 1.4 and when i go to /dav through all of the methods none of them load a page it is just blank or cannot connect. I am able to get to the web ui no problem. just adding /dav doesn't work. Tried safari and chrome on mac and Edge on windows. AM I missing something?

**Comment by mozzwald** [comment]
@sideburn try using a proper webdav client like https://cyberduck.io or similar

**Comment by mozzwald** [comment]
> Thank you! This is awesome. Been looking for a way to manage the SD card without having to remove it and this does everything I need. Gave the device a hostname and i'm good to go even if the ip changes, sweet! :)

Great! Glad you got it going
